#!/bin/bash
# A script which tries to establish VPN connection at every 20 seconds.
# Written by Ertuğrul Harman @ http://ertugrulharman.com/en
# 18.03.2016

# 2021.21.31 - Aaron Hoffer
# Changed logging to work on local machine.
# Implemented a few suggestions from a linter.
# And then hacked it up almost beyond recognition. ¯\_(ツ)_/¯

# TODO: Fix the weird GNOME-or-someone-kills-my-VPN
# The symptom is that all DNS (and I think IP) dies.
# To fix it manually, run "nmcli c show" and look for an entry like this:
#     tun0                 5bd91f09-812a-45c0-afb9-f45770fcd80b  tun       tun0
# then run:
#     sudo NM_OPENVPN_USER="" NM_OPENVPN_GROUP="" VPN_ID="5bd91f09-812a-45c0-afb9-f45770fcd80b" nmcli c up $VPN_ID

if test -z "$1"; then
  echo "No command line arguments. Attempting to locate VPN UUID"
  VPN_ENTRY=$(nmcli c show | grep vpn | tr -s " ")
  FOUND_VPN=$(! test -z "$VPN_ENTRY")
  if
    [[ ! -z "${VPN_ENTRY// /}" ]]
    vpn_name=$(echo "$VPN_ENTRY" | cut -d" " -f1)
    VPN_UUID=$(echo "$VPN_ENTRY" | cut -d" " -f2)
    vpn="$VPN_UUID"
  then
    echo "Found \"$VPN_ENTRY\""
  else
    echo "No VPN entry found."
    echo "Use \"nmcli c show\" command to view the UUIDs of network connections."
    echo "Find the UUID of your VPN connection(s) and pass them in as command line arguments"
    exit 1
  fi
else
  vpn="$1"
  vpn_name="VPN"
fi

echo "VPN UUID=$vpn"

# Keep a log.
exec &> >(tee -a "$HOME/autovpn.log")

printf "\nVPN auto connection script started at $(date +"%F %T").\nLog file is located at ${HOME}/autovpn.log\nIt will only report when no connection is found.\n"

while true
do
  sleep 5
  active_vpn=$(nmcli c show --active | grep tun0)
  if [ "$active_vpn" = "" ]; then
    printf "\n$(date +"%F %T") : VPN connection is not active!\n"
    printf "\n*** Connecting to ${vpn_name}... ***\n"
    # This is the command that start the VPN connection
    nmcli c up "${vpn}"
    if [ $? -eq 0 ]; then
      printf "\n*** Connected to ${vpn_name}! ***\n\nIt will be periodically checked to see if it is still connected.\n"
    fi
  fi
done
