#! /bin/bash
#
# Google Photos Backup
#
# Backup Google Photos to a specified local directory using gphotossync.
# Requires destination path as first argument and validates before proceeding.

if [ -z "$1" ]; then
	echo Missing destination. Pass destination as first  arg.
	echo For example \"/media/aaron/HOFFER_2/gphotos/\"
	echo Exiting now. No backup performed.
	exit 1
else
	echo Backing up google photos to \""$1"\"
fi

gphotossync "$1"
