#!/usr/bin/env bash
#
# Docker Container List All Filter
#
# List all Docker containers (including stopped ones) filtered by name with detailed output including ports.

ARGS="$1"
echo
docker container ls -a  --format='table {{.ID}}\t{{.Names}}\t{{.RunningFor}}\t{{.Status}}\t{{.Ports}}' --filter "name=$ARGS"
echo

