#!/usr/bin/env bash
#
# Docker Container List Filter
#
# List Docker containers filtered by name with formatted output showing ID, names, running time, and status.

ARGS="$1"
echo
#docker container ls --format='table {{.ID}}\t{{.Names}}\t{{.RunningFor}}\t{{.Status}}\t{{.Ports}}' --filter "name=$ARGS"
docker container ls --format='table {{.ID}}\t{{.Names}}\t{{.RunningFor}}\t{{.Status}}' --filter "name=$ARGS"
echo

