#!/bin/bash
#
# Docker Kill All Except
#
# Stop and remove all Docker containers except those containing "bambustudio" in their name.
# Useful for cleaning up development environments while preserving specific containers.

# Stop all running containers except "my-container"
docker container stop $(
  docker container ps --format '{{.ID}} {{.Names}}' \
    | grep -v "bambustudio" \
    | awk '{print $1}'
) 2>/dev/null

# Remove all containers except "my-container"
docker container rm $(
  docker container ps -a --format '{{.ID}} {{.Names}}' \
    | grep -v "bambustudio" \
    | awk '{print $1}'
) 2>/dev/null
