#!/bin/bash

# Open a shell in a container, given the partial name of the container

container=$1
shift

# Check for -u flag
user_flag=""
if [[ "$1" == "-u" && -n "$2" ]]; then
    user_flag="-u $2"
    shift 2
fi

# Build the command
cmd="docker exec -it $user_flag \$name sh"
if [[ $# -gt 0 ]]; then
    cmd="$cmd -c \"$*\""
fi

# Execute using dockerutil
python3 -c "
import sys
import os
# Add the script's directory to Python path
script_dir = os.path.dirname(os.path.abspath('$0'))
sys.path.insert(0, script_dir)
from dockerutil import execute_docker
execute_docker('$cmd', '$container')
"
