#!/usr/bin/env bash
#
# Docker Service List
#
# List Docker services with formatted output showing ID, name, and ports. Supports optional filtering by service name.

ARGS="$@"

if [[ ! -z "${ARGS}" ]]
  then
      NAME=$(docker service ls  --format='{{.Names}}' | grep $ARGS)
fi
echo
docker service ls --format='table {{.ID}}\t{{.Name}}\t{{.Ports}}' --filter "name=$NAME"
echo