#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Google OAuth Library Tool
#
# Python wrapper for Google OAuth library command-line tools. Provides
# authentication and authorization utilities for Google APIs.

import re
import sys
from google_auth_oauthlib.tool.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
