#!/bin/bash
#
# Java Process Killer
#
# Find and forcefully terminate all Java processes except the JPS process itself.
# Uses jps to identify Java processes and kills them with SIGKILL.

# Get the list of Java processes except the Jps process
PIDS=$(jps | grep -iv " jps" | awk '{print $1}')

# Kill each process
for pid in $PIDS; do
    kill -9 "$pid"
done
