#!/usr/bin/env python3
"""kshell - open a shell or run a command in a matching pod/container.

Usage: kshell [-n NAMESPACE] [-c CONTAINER] <pod-regex> [-- CMD ...]

Examples:
  kshell myapp
  kshell -n prod myapp
  kshell -c sidecar myapp -- whoami

Env:
  WAIT_SECS  seconds to wait for pod Ready (default 60)
"""

import argparse
import os
import sys

from k8s_lib import die, print_info, resolve_container, resolve_pod, run_command


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Open a shell in a matching pod/container",
        usage="kshell [-n NAMESPACE] [-c CONTAINER] REGEX [-- CMD ...]",
    )
    parser.add_argument('-n', '--namespace')
    parser.add_argument('-c', '--container')

    # Split on -- so everything after it becomes the remote command
    argv = sys.argv[1:]
    if '--' in argv:
        sep = argv.index('--')
        before, after = argv[:sep], argv[sep + 1:]
    else:
        before, after = argv, []

    args, positional = parser.parse_known_args(before)
    if not positional:
        parser.print_help(sys.stderr)
        sys.exit(1)

    pod_regex = positional[0]
    remote_cmd = after if after else ['/bin/sh']

    namespace, pod = resolve_pod(pod_regex, args.namespace)

    # Best-effort wait for Ready
    wait_secs = os.environ.get('WAIT_SECS', '60')
    run_command(
        ['kubectl', '-n', namespace, 'wait', '--for=condition=Ready',
         f'pod/{pod}', f'--timeout={wait_secs}s'],
        check=False, capture_output=True,
    )

    container = resolve_container(pod, namespace, args.container)

    # TTY flags: always -i, add -t only when both stdin and stdout are ttys
    tty_flags = ['-i']
    if sys.stdin.isatty() and sys.stdout.isatty():
        tty_flags.append('-t')

    print_info(f"Opening shell in {pod}/{container} (ns:{namespace})")
    cmd = ['kubectl', '-n', namespace, 'exec'] + tty_flags + [pod, '-c', container, '--'] + remote_cmd
    os.execvp('kubectl', cmd)


if __name__ == '__main__':
    main()
