#!/usr/bin/env perl
use strict;
use warnings;

# Downgrade the detached-HEAD branch lookup warning emitted by
# buildnumber-maven-plugin so it does not crowd the warning stream.

$| = 1;

while (my $line = <STDIN>) {
    if ($line =~ /^((?:\S+\s+)?)WARNING(\s+Cannot get the branch information from the git repository: Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref\s*)$/) {
        my ($prefix, $msg) = ($1, $2);
        chomp $msg;
        $line = $prefix . 'DEBUG' . $msg . "\n";
    }
    print $line;
}
