#!/usr/bin/env perl
use strict;
use warnings;

$| = 1;

# Joins continuation lines to their tagged header line, then adds blank
# lines before module headers and the build outcome section.
# Streams output one line at a time so progress is visible during long builds.

my $buf;
my $last_was_blank = 0;

sub emit {
    my ($blank_before) = @_;
    return unless defined $buf;
    if ($blank_before && !$last_was_blank) {
        print "\n";
    }
    print $buf;
    $last_was_blank = 0;
    $buf = undef;
}

while (my $line = <STDIN>) {
    if ($line =~ /^\[/) {
        my $needs_blank = $line =~ /^\[INFO\] (?:Building |Reactor Summary|BUILD )/;
        emit($needs_blank);
        $buf = $line;
    } elsif (defined $buf && $line =~ /\S/) {
        chomp $buf;
        $buf =~ s/\s+$//;
        (my $cont = $line) =~ s/^\s+//;
        $cont =~ s/\s+$//;
        $buf .= " $cont\n";
    }
    # Blank continuation lines are dropped.
}
emit(0);
