#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
binmode STDIN, q{:encoding(UTF-8)};
binmode STDOUT, q{:encoding(UTF-8)};
$|=1;
while(my $line=<STDIN>){
  if($line =~ /^(\S+\s+(?:INFO|WARNING|ERROR|DEBUG)\s+DOCKER>\s+)(.*)$/){
    my($p,$m)=($1,$2);
    $m =~ s/➤\s+YN\d{4}:\s+[·┌└│]\s+//g;
    $m =~ s/\s+/ /g;
    $m =~ s/^\s+|\s+$//g;
    next if $m eq '';
    next if $m =~ /^(?:Yarn\s+\S+|Resolution step|Fetch step|Link step|Post-resolution validation|Completed(?:\s+in\s+.+)?)$/;
    $line = $p.$m."\n";
  }
  print $line;
}
