#!/bin/bash
# Invoke with source - source java

mapfile -t all < <(find /usr/lib/jvm \( -name "java" -o -name "javac" \) | xargs dirname | xargs dirname | sort -u)
i=0
for path in "${all[@]}"; do
  if [[ $path =~ /(java-[0-9]+) ]]; then
    printf "[%d] %s\n" "$i" "${BASH_REMATCH[1]}"
    ((i++))
  fi
done

read -rp "Select Java version (0-$((i - 1))): " user_selection
if ! [[ "$user_selection" =~ ^[0-9]+$ ]] || ((user_selection < 0 || user_selection >= i)); then
  echo "Invalid selection" >&2
  exit 1
fi
new_java_home=${all[user_selection]}

sed -i.bak '/^[[:space:]]*export JAVA_HOME=/d' "$HOME/.bashrc"
echo "export JAVA_HOME=\"$new_java_home\"" >>"$HOME/.bashrc"
export JAVA_HOME="$selected_java_path"
source "$HOME/.bashrc"
$JAVA_HOME/bin/java -version
