#! /bin/bash
#
# Network Port Scanner
#
# Display listening network ports and associated processes.

if command -v ss >/dev/null 2>&1; then
  sudo ss -lntp
else
  sudo lsof -i 4 -P -n # | grep LISTEN
fi
