#!/bin/bash

# Print information about the remote branches
#
#   Author                    Commit Age           Branch
#   ------                    ----------           ------
#   coldrack                  4 months ago         origin/hatteras-update
#   coldrack                  4 months ago         origin/ocx-1237
#   Heron Jopts              37 minutes ago       origin/more-itests
#   Heron Jopts              5 days ago           origin/mac-redirect

# Create an array to hold the output
output=()

# Loop through all remote branches
for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/); do
  # Get the author of the last commit in the branch
  last_commit_author=$(git log -1 --format='%an' "$branch")

  # Get the age of the last commit in the branch
  last_commit_age=$(git log -1 --format='%ar' "$branch")
  last_commit_timestamp=$(git log -1 --format='%at' "$branch")

  # Add the author, timestamp, age, and branch to the array, using a delimiter (|)
  output+=("$last_commit_author|$last_commit_timestamp|$last_commit_age|$branch")
done

# Sort the output first by author lexically, then by the commit timestamp
sorted_output=$(printf "%s\n" "${output[@]}" | sort -t '|' -k1,1 -k2,2nr)

# Print the headers
printf "%-25s %-20s %-50s\n" "Last Commit" "Commit Age" "Branch"
printf "%-25s %-20s %-50s\n" "-----------" "----------" "------"

# Format and print the output
echo "$sorted_output" | while IFS='|' read -r author timestamp age branch; do
  printf "%-25s %-20s %-50s\n" "$author" "$age" "$branch"
done

