#! /bin/bash

(echo $1 | grep "^mesos-" >/dev/null) || {
  echo "ERROR: arg1 must be the mesos container name, from a Jenkins job/step! (EXAMPLE: mesos-jenkins-c84e5238-linux-large)"
  return 1
}
for MYCID in $(swarm ps | awk '/jenkins-maven/ {print $1}'); do
  if [ $(swarm inspect --format='{{.Config.Hostname}}' ${MYCID}) = "$1" ]; then
    echo "CID: ${MYCID}"
    swarm exec -it ${MYCID} bash
    break
  fi
done
