#!/usr/bin/bash
#volumes_to_remove=$(docker volume ls -q | grep -iv "aitr" | grep -iv "semantic")
volumes_to_remove=$(docker volume ls -q)
if [ ! -z "$volumes_to_remove" ]; then
    echo "$volumes_to_remove" | while read volume; do
        docker volume rm "$volume"
    done
fi
