#! /bin/bash
# A value of 175 is average

# If no arguments are provided, display help message and exit
if [ $# -eq 0 ]; then
    echo "Specifiy a zoom factor. A value of 175 is average"
    exit 1
fi

DEVICE=$(v4l2-ctl --list-devices | grep -A 1 Brio | tail -n 1 | tr -d "\t")
echo Found $DEVICE
v4l2-ctl -d $DEVICE --set-ctrl=zoom_absolute=$1
