#! /bin/bash
#
# Video Zoom Control
#
# Control the zoom level of a Logitech Brio webcam using v4l2-ctl. Automatically
# detects the device and sets the zoom_absolute control value.

# A value of 175 is average

# If no arguments are provided, display help message and exit
if [ $# -eq 0 ]; then
    echo "Specifiy a zoom factor. A value of 175 is average"
    exit 1
fi

DEVICE=$(v4l2-ctl --list-devices | grep -A 1 Brio | tail -n 1 | tr -d "\t")
echo Found $DEVICE
v4l2-ctl -d $DEVICE --set-ctrl=zoom_absolute=$1
