# Warm Medium Gray (custom)
background            #565250
foreground            #d8d8d8
cursor                #d8d8d8
cursor_text_color     #565250
selection_background  #6e6a64
selection_foreground  #d8d8d8

color0   #4e4a46
color8   #a89f96
color1   #f49090
color9   #ffaeae
color2   #a8d280
color10  #bfe49c
color3   #e0c070
color11  #ffd890
color4   #94c6d8
color12  #b4d8e8
color5   #b878b8
color13  #d090d0
color6   #84d0d0
color14  #90d8d8
color7   #c8c4bc
color15  #d8d8d8
