# Warm Medium Gray (custom)
background            #4e4a46
foreground            #d8d8d8
cursor                #d8d8d8
cursor_text_color     #4e4a46
selection_background  #6e6a64
selection_foreground  #d8d8d8

color0   #4e4a46
color8   #7a7672
color1   #e07070
color9   #ff9090
color2   #90b870
color10  #b0d890
color3   #e0c070
color11  #ffd890
color4   #80afc0
color12  #a0c8d8
color5   #c080c0
color13  #e0a0e0
color6   #70c0c0
color14  #90d8d8
color7   #c8c4bc
color15  #d8d8d8
